# Generated by Django 3.2.4 on 2023-06-29 12:59

from django.db import migrations, models
import functools
import testy.utils as utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_ci_username_duplicates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=functools.partial(utils.get_media_file_path, *(), **{'media_name': 'avatars'})),
        ),
    ]
