# TestY TMS - Test Management System
# Copyright (C) 2024 KNS Group LLC (YADRO)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Also add information on how to contact you by electronic and paper mail.
#
# If your software can interact with users remotely through a computer
# network, you should also make sure that it provides a way for users to
# get its source.  For example, if your program is a web application, its
# interface could display a "Source" link that leads users to an archive
# of the code.  There are many ways you could offer source, and different
# solutions will be better for different programs; see section 13 for the
# specific requirements.
#
# You should also get your employer (if you work as a programmer) or school,
# if any, to sign a "copyright disclaimer" for the program, if necessary.
# For more information on this, and how to apply and follow the GNU AGPL, see
# <http://www.gnu.org/licenses/>.

"""
Django settings for testy project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import json
import os
from datetime import timedelta
from pathlib import Path

import pluggy
from django.utils.translation import gettext_lazy as _

from testy.plugins import hooks
from testy.utilities.settings import add_mimetypes
from testy.utilities.string import parse_bool_from_str

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

VERSION = '2.0.5'

loaded_hosts = os.environ.get('ALLOWED_HOSTS', [])
csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', [])

add_mimetypes(os.environ.get('CUSTOM_MIMETYPES'))

ALLOWED_HOSTS = json.loads(loaded_hosts) if loaded_hosts else loaded_hosts
CSRF_TRUSTED_ORIGINS = json.loads(csrf_origins) if csrf_origins else csrf_origins

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')

REDIS_PORT = os.environ.get('REDIS_PORT')
REDIS_HOST = os.environ.get('REDIS_HOST')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'drf_yasg',
    'django_celery_beat',
    'mptt',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'simple_history',
    'celery',
    'celery_progress',
    'notifications',
    'channels',
    'pgtrigger',
    # TestY apps
    'core',
    'comments',
    'users',
    'tests_description',
    'tests_representation',
    'root',
]

TESTY_PLUGINS = [
    'testrail_migrator',
    'allure_uploader',
    'plugin_example',
]
# Defines if response should be served as nginx redirection
TESTY_ALLOW_FILE_RESPONSE = parse_bool_from_str(os.getenv('TESTY_ALLOW_FILE_RESPONSE', 'True'))
# Attachment default thumbnail resolutions
TESTY_THUMBNAIL_RESOLUTIONS = [
    (16, 16),
    (32, 32),
    (180, 180),
    (512, 512),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'testy.root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'root.wsgi.application'
ASGI_APPLICATION = 'root.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                (
                    REDIS_HOST,
                    REDIS_PORT,
                ),
            ],
            'channel_capacity': {
                'notifications': 3000,
            },
        },
    },
}
# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_SERVICE_HOST'),
        'PORT': os.environ.get('POSTGRES_SERVICE_PORT'),
        'DISABLE_SERVER_SIDE_CURSORS': True,
    },
}

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'testy.users.validators.TestyPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('en', _('English')),
    ('ru', _('Russian')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/testy-static/'
STATIC_ROOT = 'testy-static'

# extensions should be specified with dot (.txt). If no extensions specified all extensions are allowed.
ALLOWED_FILE_EXTENSIONS = []

MEDIA_URL = '/media/'
MEDIA_ROOT = 'media'  # noqa: F405

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'
AUTH_TOKEN_TTL = 365  # in days
CHAR_FIELD_MAX_LEN = 255
FILEPATH_MAX_LEN = 150
TOKEN_MAX_LEN = 40
MIN_VALUE_POSITIVE_INTEGER = 0

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django REST framework (API)
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'testy.root.auth.TokenAuthenticationTTL',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'NON_FIELD_ERRORS_KEY': 'errors',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    # 'ALLOWED_VERSIONS': ['v1', 'v2']
}
# NamespaceVersioning
# URLPathVersioning
ACCESS_TOKEN_LIFETIME: timedelta(minutes=60)

# Django CORS headers
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True

# Company
COMPANY_DOMAIN = os.environ.get('COMPANY_DOMAIN')

SESSION_COOKIE_AGE = 12 * 60 * 60  # 12 hours

SESSION_COOKIE_AGE_REMEMBER_ME = 365 * 24 * 60 * 60  # 365 days

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '%(asctime)s - %(module)s - %(levelname)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'formatter': 'default',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'gunicorn': {
            'handlers': ['console'],
            'level': os.getenv('GUNICORN_LOG_LEVEL', 'INFO'),
        },
        'gunicorn.errors': {
            'handlers': ['console'],
            'level': os.getenv('GUNICORN_ERROR_LOG_LEVEL', 'INFO'),
        },
        'gunicorn.access': {
            'handlers': ['console'],
            'level': os.getenv('GUNICORN_ACCESS_LOG_LEVEL', 'INFO'),
        },
        'celery': {
            'handlers': ['console'],
            'level': os.getenv('CELERY_LOG_LEVEL', 'INFO'),
        },
        'core': {
            'handlers': ['console'],
            'level': os.getenv('CORE_LOG_LEVEL', 'INFO'),
        },
        '': {
            'handlers': ['console'],
            'level': os.getenv('ROOT_LOG_LEVEL', 'INFO'),
        },
    },
}

CACHE_TTL = 60 * 5  # in seconds

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}',  # noqa F405
        'TIMEOUT': CACHE_TTL,
    },
}

PROJECT_PROGRESS_FILTER_PERIOD_IN_DAYS = 7
WORK_HOURS = 8  # how many hours in work day, variable is used to process estimates

SWAGGER_SETTINGS = {'DEFAULT_AUTO_SCHEMA_CLASS': 'swagger.custom_schema_generation.TestyAutoSchema'}

# Plugins configuration
plugin_manager = pluggy.PluginManager('testy')
plugin_manager.add_hookspecs(hooks.PluginEntrypointHookSpecs)
plugin_manager.load_setuptools_entrypoints('testy')

PLUGIN_CONFIGS: list[hooks.TestyPluginConfig] = [config for config in plugin_manager.hook.config() if config.is_valid()]

for config in PLUGIN_CONFIGS:
    INSTALLED_APPS.append(config.package_name)
    if config.middlewares:
        MIDDLEWARE.extend(config.middlewares)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

ADMIN_ROLE_NAME = 'Admin'

IS_RESULT_EDITABLE = True
RESULT_EDIT_LIMIT = 60 * 60

DJANGO_NOTIFICATIONS_CONFIG = {'USE_JSONFIELD': True}

PROMETHEUS_MULTIPROC_DIR = os.getenv('prometheus_multiproc_dir')
