# Generated by Django 3.2.4 on 2023-02-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0010_added_updated_choices_to_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='parameters_m2m',
            field=models.ManyToManyField(blank=True, related_name='test_plans', to='tests_representation.Parameter'),
        ),
    ]
