# Generated by Django 3.2.4 on 2023-02-16 19:13

from django.db import migrations


def set_test_plan_m2m_parameters(apps, schema_editor):
    test_plan_model = apps.get_model('tests_representation', 'TestPlan')
    parameter_model = apps.get_model('tests_representation', 'Parameter')
    for test_plan in test_plan_model.objects.all():
        if not test_plan.parameters:
            continue

        parameters = parameter_model.objects.filter(pk__in=test_plan.parameters)
        test_plan.parameters_m2m.set(parameters)


def set_test_plan_list_parameters(apps, schema_editor):
    test_plan_model = apps.get_model('tests_representation', 'TestPlan')
    for test_plan in test_plan_model.objects.all():
        test_plan.parameters = list(test_plan.parameters_m2m.values_list("pk", flat=True).all())
        test_plan.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0011_added_testplan_parameters_m2m'),
    ]

    operations = [
        migrations.RunPython(
            set_test_plan_m2m_parameters,
            set_test_plan_list_parameters
        )
    ]
