# Generated by Django 3.2.4 on 2023-02-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0012_updated_testplan_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='parameters',
        ),
    ]
