# Generated by Django 3.2.4 on 2023-02-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0013_remove_testplan_parameters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testplan',
            old_name='parameters_m2m',
            new_name='parameters',
        ),
    ]
