# Generated by Django 3.2.4 on 2023-03-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0014_rename_parameters_m2m_testplan_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tests_representation.test'),
        ),
    ]
