# Generated by Django 3.2.4 on 2023-03-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content_type_and_object_id_is_not_required'),
        ('tests_representation', '0015_added_related_name_to_testresult_test'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('group_name', 'data', 'project')},
        ),
    ]
