# Generated by Django 3.2.4 on 2023-04-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_content_type_and_object_id_is_not_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests_description', '0003_added_testcasesteps'),
        ('tests_representation', '0016_alter_parameter_unique_together_for_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.IntegerField(choices=[
                 (0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest')], default=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='result', to='tests_description.testcasestep')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='steps_results', to='tests_representation.testresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTestStepResult',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('status', models.IntegerField(choices=[
                 (0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest')], default=5)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'),
                 ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.project')),
                ('step', models.ForeignKey(blank=True, db_constraint=False, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tests_description.testcasestep')),
                ('test_result', models.ForeignKey(blank=True, db_constraint=False, null=True,
                 on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tests_representation.testresult')),
            ],
            options={
                'verbose_name': 'historical test step result',
                'verbose_name_plural': 'historical test step results',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
