# Generated by Django 4.2.13 on 2024-08-09 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0015_alter_historicaltestcase_estimate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_customattribute_status_specific_and_more'),
        ('tests_representation', '0020_alter_test_assignee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='test',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='test',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_description.testcase'),
        ),
        migrations.AlterField(
            model_name='test',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_representation.testplan'),
        ),
        migrations.AlterField(
            model_name='test',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('group_name', 'data', 'project'), name='unique_group_name_data_project_value_on_parameter_for_soft_delete'),
        ),
    ]
