# Generated by Django 4.2.13 on 2024-09-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0022_alter_testplan_level_alter_testplan_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest'), (7, 'Rollbacked')], default=5),
        ),
        migrations.AlterField(
            model_name='historicalteststepresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest'), (7, 'Rollbacked')], default=5),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest'), (7, 'Rollbacked')], default=5),
        ),
        migrations.AlterField(
            model_name='teststepresult',
            name='status',
            field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest'), (7, 'Rollbacked')], default=5),
        ),
    ]
