# Generated by Django 4.2.13 on 2024-07-30 12:18

from django.db import migrations, models, transaction
from django.utils import timezone
from testy.tests_representation.choices import TestStatuses, ResultStatusType
import django.db.models.deletion

@transaction.atomic
def create_base_system_statuses(apps, schema_editor):
    status_model = apps.get_model('tests_representation', 'ResultStatus')
    choices = {
        TestStatuses.FAILED.label: '#C44D56',
        TestStatuses.PASSED.label: '#4DAF7C',
        TestStatuses.SKIPPED.label: 'rgba(34, 34, 34, 1)',
        TestStatuses.BROKEN.label: 'rgba(160, 160, 160, 1)',
        TestStatuses.BLOCKED.label: 'rgba(208, 208, 208, 1)',
        TestStatuses.RETEST.label: '#EFB622',
        TestStatuses.ROLLBACKED.label: 'rgb(247, 225, 0)',
    }
    base_system_statuses = []
    for label, color in choices.items():
        status = status_model(name=label, type=ResultStatusType.SYSTEM, color=color)
        if label == TestStatuses.ROLLBACKED.label:
            status.is_deleted = True
            status.deleted_at = timezone.now()
        base_system_statuses.append(status)
    status_model.objects.bulk_create(base_system_statuses)


class Migration(migrations.Migration):

    dependencies = [
        # ('core', '0019_customattribute_status_specific'),
        ('tests_representation', '0023_alter_historicaltestresult_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#000000', max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'System'), (1, 'Custom')], default=1)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name': 'Result status',
                'verbose_name_plural': 'Result statuses',
            },
        ),
        migrations.RunPython(create_base_system_statuses, reverse_code=migrations.RunPython.noop),
    ]
