# Generated by Django 4.2.13 on 2024-07-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('tests_representation', '0024_resultstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestresult',
            name='status_temp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='tests_representation.resultstatus'),
        ),
        migrations.AddField(
            model_name='historicalteststepresult',
            name='status_temp',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='tests_representation.resultstatus'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='status_temp',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_representation.resultstatus'),
        ),
        migrations.AddField(
            model_name='teststepresult',
            name='status_temp',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_representation.resultstatus'),
        ),
    ]
