# Generated by Django 4.2.13 on 2024-07-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0026_move_data_for_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalteststepresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='status',
        ),
        migrations.RemoveField(
            model_name='teststepresult',
            name='status',
        ),
    ]
