# Generated by Django 4.2.13 on 2024-07-14 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tests_representation', '0027_remove_historicaltestresult_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltestresult',
            old_name='status_temp',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='historicalteststepresult',
            old_name='status_temp',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='status_temp',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='teststepresult',
            old_name='status_temp',
            new_name='status',
        ),
    ]
