# Generated by Django 4.2.13 on 2024-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0028_rename_status_temp_historicaltestresult_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
