# Generated by Django 4.2.13 on 2024-07-05 06:49

from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import testy.root.ltree.fields
from testy.root.ltree.migration_sql import create_initial_path


class Migration(migrations.Migration):
    dependencies = [
        ('tests_representation', '0030_make_mptt_field_nullable_and_assign_default_value'),
        ('testy', '0002_added_ltree')
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='testplan',
            name='rght',
        ),
        migrations.AddField(
            model_name='testplan',
            name='path',
            field=testy.root.ltree.fields.LtreeField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='child_test_plans', to='tests_representation.testplan'),
        ),
        migrations.RemoveField('testplan', 'tree_id'),
        migrations.AddField(
            model_name='testplan',
            name='tree_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, editable=False, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testplan',
            trigger=pgtrigger.compiler.Trigger(name='plan_insert_trg', sql=pgtrigger.compiler.UpsertTriggerSql(
                func='IF NEW.parent_id IS NULL THEN     NEW.path = NEW.id::text::ltree;     NEW.tree_id = NEW.id; ELSE     SELECT path || NEW.id::text, tree_id FROM tests_representation_testplan     WHERE id = NEW.parent_id INTO NEW.path, NEW.tree_id; END IF; RETURN NEW;',
                hash='5c216ce8b5c59996ae70b2185524d71939762688', operation='INSERT',
                pgid='pgtrigger_plan_insert_trg_de81a', table='tests_representation_testplan', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testplan',
            trigger=pgtrigger.compiler.Trigger(name='plan_path_change_trg', sql=pgtrigger.compiler.UpsertTriggerSql(
                condition='WHEN (OLD."parent_id" IS DISTINCT FROM (NEW."parent_id"))',
                func='IF NEW.parent_id IS NULL THEN     NEW.path = NEW.id::text::ltree;     NEW.tree_id = NEW.id; ELSE     SELECT path || NEW.id::text, tree_id FROM tests_representation_testplan     WHERE id = NEW.parent_id INTO NEW.path, NEW.tree_id; END IF; RETURN NEW;',
                hash='972456ad1a12d2cda66745d4ff937f94e7e58f97', operation='UPDATE',
                pgid='pgtrigger_plan_path_change_trg_6ecad', table='tests_representation_testplan', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testplan',
            trigger=pgtrigger.compiler.Trigger(name='plan_path_descendants_trg',
                                               sql=pgtrigger.compiler.UpsertTriggerSql(
                                                   condition='WHEN (OLD."path" IS DISTINCT FROM (NEW."path"))',
                                                   func='UPDATE tests_representation_testplan SET path = NEW.path || subpath(path, nlevel(OLD.path)),     tree_id = NEW.tree_id WHERE path <@ OLD.path AND id != NEW.id AND tree_id = OLD.tree_id; RETURN NEW;',
                                                   hash='c3cc7290d4d52a452b5716a0410ac979d4d19ad0', operation='UPDATE',
                                                   pgid='pgtrigger_plan_path_descendants_trg_d4fba',
                                                   table='tests_representation_testplan', when='AFTER')),
        ),
        migrations.RunSQL(
            create_initial_path.format(table_name='tests_representation_testplan'),
            reverse_sql='',
        ),
        migrations.AddIndex(
            model_name='testplan',
            index=django.contrib.postgres.indexes.GistIndex(models.F('path'), name='plangist_path_idx'),
        ),
    ]
