# Generated by Django 4.2.13 on 2024-10-23 12:15

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import OuterRef, Subquery, F, QuerySet

def fill_last_status(apps, schema_editor):
    TestResult = apps.get_model('tests_representation', 'TestResult')
    Test = apps.get_model('tests_representation', 'Test')
    subq = TestResult.objects.filter(test_id=OuterRef('pk')).order_by('-created_at')[:1].values('status')
    tests = Test.objects.all().annotate(last_status_annotated=Subquery(subq))
    tests.update(last_status_id=F('last_status_annotated'))


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0031_remove_testplan_level_remove_testplan_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltest',
            name='last_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tests_representation.resultstatus'),
        ),
        migrations.AddField(
            model_name='test',
            name='last_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests_representation.resultstatus'),
        ),
        migrations.RunPython(fill_last_status, migrations.RunPython.noop),
    ]
