services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - type: bind
        source: ./backend/testy/testy-static
        target: /opt/testy/testy/testy-static
      - type: volume
        source: testy_volumes
        target: /opt/testy/testy/media
        volume:
          nocopy: true
      - type: volume
        source: testy_volumes
        target: /opt/testy-frontend/build
        volume:
          nocopy: true
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - client
      - testy
  client:
    container_name: testy-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ${ENV_FILE:-.env}
    volumes:
      - '/app/node_modules'
      - type: volume
        source: testy_volumes
        target: /app/build
        volume:
          nocopy: true
    user: "${UID}:${GID}"
  testy:
    container_name: testy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: ./backend/testy
      dockerfile: scripts/Dockerfile
      args:
        - ENV=prod
    image: testy:latest
    pull_policy: build
    volumes:
      - type: volume
        source: testy_volumes
        target: /testy/media
        volume:
          nocopy: true
      - type: bind
        source: ./backend/testy/testy-static
        target: /testy/testy-static
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings.production
    ports:
      - '8001:8000'
    env_file:
      - ${ENV_FILE:-.env}
    command: scripts/entrypoint.sh
    depends_on:
      pgbouncer:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g

  db:
    container_name: testy_db
    image: postgres:14.5-alpine
    volumes:
      - type: volume
        source: testy_volumes
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ${ENV_FILE:-.env}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5435:5432'
    shm_size: '1gb'
    user: "${UID}:${GID}"

  pgbouncer:
    container_name: testy_pgbouncer
    image: edoburu/pgbouncer:1.22.1-p0
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h ${DB_HOST} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  redis:
    container_name: testy_redis
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - type: volume
        source: testy_volumes
        target: /data
        volume:
          nocopy: true
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - '6380:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    user: "${UID}:${GID}"

  celery:
    container_name: testy_celery
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
    image: testy:latest
    pull_policy: build
    command: celery -A root worker -B -l INFO
    volumes:
      - type: volume
        source: testy_volumes
        target: /testy/media
        volume:
          nocopy: true
      - type: bind
        source: ./backend/testy/testy-static
        target: /testy/testy-static
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DJANGO_SETTINGS_MODULE=root.settings.production
    healthcheck:
      test: [ "CMD-SHELL", "celery -b ${CELERY_BROKER_URL} inspect ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
      - pgbouncer
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g

  notification-worker:
    container_name: notifications
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    image: testy:latest
    pull_policy: build
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - testy
    command: python manage.py runworker notifications

volumes:
  testy_volumes:
    driver: local
    driver_opts:
      type: none
      device: /data/volumes
      o: bind


