# Generated by Django 3.2.4 on 2023-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0003_added_testcasesteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='expected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicaltestcasestep',
            name='expected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcasestep',
            name='expected',
            field=models.TextField(blank=True),
        ),
    ]
