# Generated by Django 3.2.4 on 2023-06-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0004_added_expected_to_case_and_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestcase',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='estimate',
        ),
    ]
