# Generated by Django 3.2.4 on 2023-06-14 12:23

from django.db import migrations
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0005_deleted_estimate_for_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='estimate',
            field=fields.EstimateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='estimate',
            field=fields.EstimateField(blank=True, null=True),
        ),
    ]
