# Generated by Django 3.2.4 on 2023-10-18 14:22

from django.db import migrations, models
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0007_added_is_deleted_to_suite_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='estimate_tmp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='estimate_tmp',
            field=fields.IntegerEstimateField(blank=True, null=True),
        ),
    ]
