# Generated by Django 3.2.4 on 2023-10-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0009_move_data_for_estimates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltestcase',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='estimate',
        ),
    ]
