# Generated by Django 3.2.4 on 2023-10-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0010_deleted_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltestcase',
            old_name='estimate_tmp',
            new_name='estimate',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='estimate_tmp',
            new_name='estimate',
        ),
    ]
