# Generated by Django 3.2.4 on 2023-10-26 14:16

from django.db import migrations
import fields


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0011_altered_estimate_tmp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcase',
            name='estimate',
            field=fields.IntegerEstimateField(blank=True, null=True),
        ),
    ]
