# Generated by Django 3.2.4 on 2023-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0012_alter_historicaltestcase_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
