# Generated by Django 3.2.4 on 2024-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0013_auto_20231102_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testcase',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
