# Generated by Django 4.2.13 on 2024-08-09 10:21

from django.db import migrations, models
import django.db.models.deletion
import testy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customattribute_status_specific_and_more'),
        ('tests_description', '0014_auto_20240605_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcase',
            name='estimate',
            field=testy.fields.IntegerEstimateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='estimate',
            field=testy.fields.IntegerEstimateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
