# Generated by Django 4.2.13 on 2024-10-24 18:22

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0018_remove_testsuite_level_remove_testsuite_lft_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_increment_statistics_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count + 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='cb1db4c9c0c19c296c2d6915d12756c34156ea41', operation='INSERT', pgid='pgtrigger_cases_count_increment_statistics_on_insert_40b29', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_decrement_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NEW."is_deleted" AND NOT OLD."is_deleted") OR (NEW."is_archive" AND NOT OLD."is_archive"))', func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count - 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='05efe33e05924ddc194f253b78fe3d31ff0b1981', operation='UPDATE', pgid='pgtrigger_cases_count_decrement_statistics_on_update_ed1bc', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_increment_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN ((NOT NEW."is_deleted" AND OLD."is_deleted") OR (NOT NEW."is_archive" AND OLD."is_archive"))', func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count + 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='0e9de6c0a7ba4912833d245daa1fb3b98ce62ca1', operation='UPDATE', pgid='pgtrigger_cases_count_increment_statistics_on_update_c529f', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testcase',
            trigger=pgtrigger.compiler.Trigger(name='cases_count_decrement_statistics_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE core_projectstatistics \n            SET cases_count = cases_count - 1 \n            WHERE project_id = OLD.project_id;\n            RETURN OLD;\n            ', hash='7ef0db2ed2396a308a7f73799e449d63ce5b1338', operation='DELETE', pgid='pgtrigger_cases_count_decrement_statistics_on_delete_9e1e1', table='tests_description_testcase', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testsuite',
            trigger=pgtrigger.compiler.Trigger(name='suites_count_increment_statistics_on_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE core_projectstatistics \n            SET suites_count = suites_count + 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='3c886a6d0b0b7e14236012691ab6be4fe4ad2827', operation='INSERT', pgid='pgtrigger_suites_count_increment_statistics_on_insert_e98cb', table='tests_description_testsuite', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testsuite',
            trigger=pgtrigger.compiler.Trigger(name='suites_count_decrement_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NEW."is_deleted" AND NOT OLD."is_deleted")', func='\n            UPDATE core_projectstatistics \n            SET suites_count = suites_count - 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='c248c45705afcff5f2702f217aa48d4ac16eac54', operation='UPDATE', pgid='pgtrigger_suites_count_decrement_statistics_on_update_27278', table='tests_description_testsuite', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testsuite',
            trigger=pgtrigger.compiler.Trigger(name='suites_count_increment_statistics_on_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (NOT NEW."is_deleted" AND OLD."is_deleted")', func='\n            UPDATE core_projectstatistics \n            SET suites_count = suites_count + 1 \n            WHERE project_id = NEW.project_id;\n            RETURN NEW;\n            ', hash='fffe9927b6dd0de0244592b7ae67cd3ce63c728d', operation='UPDATE', pgid='pgtrigger_suites_count_increment_statistics_on_update_e3a13', table='tests_description_testsuite', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testsuite',
            trigger=pgtrigger.compiler.Trigger(name='suites_count_decrement_statistics_on_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n            UPDATE core_projectstatistics \n            SET suites_count = suites_count - 1 \n            WHERE project_id = OLD.project_id;\n            RETURN OLD;\n            ', hash='1ef6856db3da01b332d17f8a45b8a81d4f7b72fb', operation='DELETE', pgid='pgtrigger_suites_count_decrement_statistics_on_delete_c8363', table='tests_description_testsuite', when='BEFORE')),
        ),
    ]
