# Generated by Django 4.2.13 on 2024-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_description', '0020_remove_testcase_cases_count_increment_statistics_on_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
