# Generated by Django 3.2.4 on 2023-03-31 14:58

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testy', '0001_initial'),
    ]

    operations = [
        CreateExtension('ltree'),
    ]
