# Generated by Django 3.2.4 on 2023-07-25 07:28

from django.db import migrations, models
import functools
import testy.utils as utils
import testy.validators as validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_added_soft_delete_fields_to_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=150, upload_to=functools.partial(utils.get_media_file_path, *(), **{'media_name': 'attachments'}), validators=[validators.ExtensionValidator()]),
        ),
    ]
