# Generated by Django 3.2.4 on 2023-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('content', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'Info'), (1, 'Warning'), (2, 'Critical')])),
                ('is_active', models.BooleanField(default=False)),
                ('is_closing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System message',
                'verbose_name_plural': 'System messages',
            },
        ),
    ]
