# Generated by Django 3.2.4 on 2023-09-18 12:17

from django.db import migrations, models
import functools
import testy.utils as utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=functools.partial(utils.get_media_file_path, *(), **{'media_name': 'icons'})),
        ),
    ]
