# Generated by Django 3.2.4 on 2023-11-13 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='content_object_history_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
