# Generated by Django 3.2.4 on 2024-06-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240605_0710'),
        ('users', '0005_auto_20240605_0710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='users.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='unique_project_name_value_on_label_for_soft_delete'),
        ),
        migrations.AddField(
            model_name='customattribute',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.project'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='unique_project_name_value_on_custom_attribute_for_soft_delete'),
        ),
    ]
