# Generated by Django 4.2.13 on 2024-08-09 10:21

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import testy.tests_representation.choices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20240605_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='customattribute',
            name='status_specific',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest')]), default=testy.tests_representation.choices.TestStatuses.cb_values, size=None),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action_code', models.IntegerField(choices=[(0, 'Test assigned'), (1, 'Test unassigned'), (2, 'Test case modified'), (3, 'Test plan modified')], primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder_text', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder_link', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(max_length=255)),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'notification_settings',
            },
        ),
    ]
