# Generated by Django 4.2.13 on 2024-09-11 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customattribute_status_specific_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customattribute',
            name='status_specific',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
    ]
