# Generated by Django 4.2.13 on 2024-09-04 16:15

import django.contrib.postgres.fields
from django.db import migrations, models
import testy.tests_representation.choices


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customattribute_status_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customattribute',
            name='status_specific',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Failed'), (1, 'Passed'), (2, 'Skipped'), (3, 'Broken'), (4, 'Blocked'), (5, 'Untested'), (6, 'Retest'), (7, 'Rollbacked')]), default=testy.tests_representation.choices.TestStatuses.cb_values, size=None),
        ),
    ]