# Generated by Django 4.2.13 on 2024-07-28 15:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_representation', '0024_resultstatus'),
        ('core', '0016_alter_customattribute_status_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='customattribute',
            name='status_specific_temp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
    ]
