# Generated by Django 4.2.13 on 2024-07-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customattribute_change_status_specific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customattribute',
            name='status_specific',
        ),
    ]
