# Generated by Django 4.2.13 on 2024-07-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_customattribute_status_specific'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customattribute',
            old_name='status_specific_temp',
            new_name='status_specific',
        ),
    ]
