# Generated by Django 4.2.13 on 2024-11-14 15:53

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_projectstatistics_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='project',
            name='insert_statistics_on_project_create',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='project',
            trigger=pgtrigger.compiler.Trigger(name='insert_statistics_on_project_create', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                INSERT INTO core_projectstatistics\n                (project_id, cases_count, suites_count, tests_count, plans_count, is_deleted)\n                VALUES (NEW.id, 0, 0, 0, 0, FALSE);\n                RETURN NEW;\n                ', hash='644c2389bae72e9d46b012a4e79e860b416f89c0', operation='INSERT', pgid='pgtrigger_insert_statistics_on_project_create_edc58', table='core_project', when='BEFORE')),
        ),
    ]
