# Generated by Django 4.2.13 on 2025-01-13 16:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_project_insert_statistics_on_project_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customattribute',
            name='applied_to',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customattribute',
            name='content_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
    ]
