# Generated by Django 4.2.13 on 2025-01-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_moving_custom_attributes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customattribute',
            name='content_types',
        ),
        migrations.RemoveField(
            model_name='customattribute',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='customattribute',
            name='is_suite_specific',
        ),
        migrations.RemoveField(
            model_name='customattribute',
            name='status_specific',
        ),
        migrations.RemoveField(
            model_name='customattribute',
            name='suite_ids',
        ),
    ]
